# Generated by Django 4.0.1 on 2022-01-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99, verbose_name='Пример кода')),
                ('html_code', models.TextField(blank=True, verbose_name='Html код')),
                ('css_code', models.TextField(blank=True, verbose_name='Css код')),
                ('js_code', models.TextField(blank=True, verbose_name='Js код')),
            ],
        ),
    ]
