# Generated by Django 4.0.1 on 2022-01-23 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_codeexample'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99, unique=True, verbose_name='название домена')),
                ('beget_id', models.IntegerField(unique=True, verbose_name='id домена на beget')),
                ('description', models.TextField(blank=True, max_length=999, verbose_name='доп. информация')),
                ('facebook', models.CharField(choices=[('NEW', 'Новый'), ('USE', 'Запускался'), ('BAN', 'Забанен')], default='NEW', max_length=99)),
                ('google', models.CharField(choices=[('NEW', 'Новый'), ('USE', 'Запускался'), ('BAN', 'Забанен')], default='NEW', max_length=99)),
                ('tiktok', models.CharField(choices=[('NEW', 'Новый'), ('USE', 'Запускался'), ('BAN', 'Забанен')], default='NEW', max_length=99)),
            ],
        ),
        migrations.CreateModel(
            name='RootDomain',
            fields=[
                ('domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='office.domain')),
                ('is_full', models.BooleanField(default=False, verbose_name='Привышен ли лимит поддоменов')),
            ],
            bases=('office.domain',),
        ),
        migrations.CreateModel(
            name='SubDomain',
            fields=[
                ('domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='office.domain')),
                ('root_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.rootdomain')),
            ],
            bases=('office.domain',),
        ),
    ]
