# Generated by Django 4.0.1 on 2022-01-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_domain_rootdomain_subdomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название оффера')),
            ],
        ),
    ]
