# Generated by Django 4.0.1 on 2022-01-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0005_alter_offerposition_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyPaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название копипасты')),
                ('data', models.JSONField(default=dict)),
            ],
        ),
    ]
