# Generated by Django 4.0.1 on 2022-01-26 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0006_copypaste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copypaste',
            name='data',
        ),
        migrations.CreateModel(
            name='CopyPasteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('data', models.TextField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.copypaste')),
            ],
        ),
    ]
