# Generated by Django 4.0.1 on 2022-01-31 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0008_alter_copypaste_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название страны')),
                ('short_name', models.CharField(max_length=3)),
                ('lang', models.CharField(max_length=5, verbose_name='Код языка страны')),
                ('phone_code', models.IntegerField()),
                ('names', models.JSONField(default={'names': []})),
            ],
        ),
        migrations.AlterField(
            model_name='copypastedata',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='office.copypaste'),
        ),
    ]
