# Generated by Django 4.0.1 on 2022-01-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0009_country_alter_copypastedata_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.CharField(blank=True, max_length=10, verbose_name='Валюта страны'),
        ),
    ]
