# Generated by Django 4.0.1 on 2022-01-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0010_country_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='phone_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
