# Generated by Django 4.0.1 on 2022-05-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название Сайта')),
                ('description', models.CharField(max_length=200, verbose_name='Описание сайта')),
                ('dir_path', models.CharField(max_length=100, verbose_name='Пусть к сайту')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
