# Generated by Django 4.0.1 on 2022-05-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_alter_site_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Категория сайта'),
        ),
        migrations.AddField(
            model_name='site',
            name='language',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Язык сайта'),
        ),
    ]
