# Generated by Django 4.0.1 on 2022-05-09 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_site_category_site_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteCategoty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название категории')),
            ],
        ),
        migrations.AlterField(
            model_name='site',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.sitecategoty', verbose_name='Категория сайта'),
        ),
    ]
