# Generated by Django 4.0.1 on 2022-05-09 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_sitecategoty_alter_site_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='category',
        ),
    ]
