# Generated by Django 4.0.1 on 2022-05-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0006_site_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='dir_path',
            field=models.CharField(max_length=100, unique=True, verbose_name='Пусть к сайту'),
        ),
    ]
