# Generated by Django 4.0.1 on 2022-05-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0007_alter_site_dir_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(max_length=2, verbose_name='Короткое название')),
                ('full', models.CharField(max_length=20, verbose_name='полное название')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
