# Generated by Django 4.0.1 on 2022-05-13 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0012_site_cataloge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=20, verbose_name='Текст')),
                ('smile', models.CharField(blank=True, max_length=10, verbose_name='Смайлик')),
            ],
        ),
        migrations.AlterField(
            model_name='site',
            name='languege',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.languege', verbose_name='Язык сайта'),
        ),
        migrations.AddField(
            model_name='cataloge',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.tag'),
        ),
        migrations.AddField(
            model_name='site',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.tag'),
        ),
    ]
