# Generated by Django 4.0.1 on 2022-05-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0013_tag_alter_site_languege_cataloge_tag_site_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cataloge',
            name='tag',
        ),
        migrations.AddField(
            model_name='cataloge',
            name='tag',
            field=models.ManyToManyField(to='archive.Tag'),
        ),
        migrations.RemoveField(
            model_name='site',
            name='tag',
        ),
        migrations.AddField(
            model_name='site',
            name='tag',
            field=models.ManyToManyField(to='archive.Tag'),
        ),
    ]
