# Generated by Django 4.0.1 on 2022-05-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0015_remove_cataloge_tag_cataloge_tag_remove_site_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='html_class',
            field=models.CharField(default='none', max_length=10, verbose_name='Класс HTML'),
            preserve_default=False,
        ),
    ]
