# Generated by Django 4.0.1 on 2022-04-21 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99, verbose_name='Пример кода')),
                ('html_code', models.TextField(blank=True, verbose_name='Html код')),
                ('css_code', models.TextField(blank=True, verbose_name='Css код')),
                ('js_code', models.TextField(blank=True, verbose_name='Js код')),
            ],
        ),
        migrations.CreateModel(
            name='CopyPaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название копипасты')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название страны')),
                ('short_name', models.CharField(max_length=3)),
                ('lang', models.CharField(max_length=5, verbose_name='Код языка страны')),
                ('phone_code', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, verbose_name='Валюта страны')),
                ('names', models.JSONField(default={'names': []})),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99, unique=True, verbose_name='название домена')),
                ('beget_id', models.IntegerField(unique=True, verbose_name='id домена на beget')),
                ('description', models.TextField(blank=True, max_length=999, verbose_name='доп. информация')),
                ('facebook', models.CharField(choices=[('NEW', 'Новый'), ('USE', 'Запускался'), ('BAN', 'Забанен')], default='NEW', max_length=99)),
                ('google', models.CharField(choices=[('NEW', 'Новый'), ('USE', 'Запускался'), ('BAN', 'Забанен')], default='NEW', max_length=99)),
                ('tiktok', models.CharField(choices=[('NEW', 'Новый'), ('USE', 'Запускался'), ('BAN', 'Забанен')], default='NEW', max_length=99)),
            ],
        ),
        migrations.CreateModel(
            name='DomCamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=50, unique=True, verbose_name='Домен')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kt_id', models.IntegerField(db_index=True)),
                ('check_status', models.CharField(default='Не проверен', max_length=30)),
                ('check_data', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfferPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название оффера')),
            ],
        ),
        migrations.CreateModel(
            name='RootDomain',
            fields=[
                ('domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='office.domain')),
                ('is_full', models.BooleanField(default=False, verbose_name='Привышен ли лимит поддоменов')),
            ],
            bases=('office.domain',),
        ),
        migrations.CreateModel(
            name='Spend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('spend', models.FloatField()),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.domcamp')),
            ],
        ),
        migrations.CreateModel(
            name='CopyPasteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('data', models.TextField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='office.copypaste')),
            ],
        ),
        migrations.CreateModel(
            name='SubDomain',
            fields=[
                ('domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='office.domain')),
                ('root_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.rootdomain')),
            ],
            bases=('office.domain',),
        ),
    ]
